apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-custom
data:
  qiyuesuo.db.itemchek: "false"
  # qiyuesuo.setup: "database"
  # qiyuesuo.setup=complete

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-default
data:
  qiyuesuo.db.itemchek: "false"
  qiyuesuo.setup: "complete"
  spring.datasource.url: "jdbc\\:mysql\://mysql\:3306/bmwdb?serverTimezone\=GMT%2B8&useUnicode\=true&useSSL\=false&characterEncoding\=utf-8&allowPublicKeyRetrieval\=true"
  spring.datasource.password: "QYS@r0P1mEUN972oy72IwKpM+jXguV6vaAxB"
