apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-custom
data:
  qiyuesuo.db.itemchek: "false"
  qiyuesuo.license.file: "./license/LICENSE"
  # qiyuesuo.setup: "database"
  # qiyuesuo.setup: "complete"
  # spring.datasource.url: "jdbc\\:mysql\://mysql\:3306/bmwdb?serverTimezone\=GMT%2B8&useUnicode\=true&useSSL\=false&characterEncoding\=utf-8&allowPublicKeyRetrieval\=true"
  # spring.datasource.password: "QYS@r0P1mEUN972oy72IwKpM+jXguV6vaAxB"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-oss
data:
  server.port: "9181"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app
data:
  server.port: 9180
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-open
data:
  server.port: 9182
