apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-custom
data:
  qiyuesuo.db.itemchek: "false"
  qiyuesuo.license.file: "./license/LICENSE"
  eureka.client.serviceUrl.defaultZone: $EUREKA_SERVER_ADDRESS
  qiyuesuo.setup: "complete"
  spring.datasource.url: "jdbc:mysql://mysql:3306/bmwdb"
  spring.datasource.username: "root"
  spring.datasource.password: "Qiyuesuo#2020"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hazelcast
data:
  server.port: "5701"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-oss
data:
  server.port: "9181"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app
data:
  server.port: "9180"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-open
data:
  server.port: "9182"
