apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-custom
data:
  qiyuesuo.db.itemchek: "false"
  qiyuesuo.license.file: "./license/LICENSE"
  # qiyuesuo.setup: "complete"
  # spring.datasource.url: "jdbc:mysql://mysql:3306/bmwdb"
  # spring.datasource.username: "root"
  # spring.datasource.password: "Qiyuesuo#2020"
  qiyuesuo.eureka.hazelcast: "true"
  qiyuesuo.cache.hazelcast.isserver: "false"
  eureka.client.register-with-eureka: "true"
  eureka.client.fetch-registry: "true"
  eureka.instance.perferIpAddress: "true"
  eureka.instance.leaseRenewalIntervalInSeconds: "5"
  eureka.instance.leaseExpirationDurationInSeconds: "10"
  eureka.client.registryFetchIntervalSeconds: "5"
  eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hazelcast
data:
  server.port: "5701"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-oss
data:
  server.port: "9181"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app
data:
  server.port: "9180"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-open
data:
  server.port: "9182"
