apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "standard-xfs-ssd-resizable"
  resources:
    requests:
      storage: 1Gi
