apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-standard-xfs-ssd-resizable
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard-xfs-ssd-resizable"
  resources:
    requests:
      storage: 1Gi
