apiVersion: v1
kind: Service
metadata:
  name: oss-np
  labels:
    app: oss
spec:
  type: NodePort
  ports:
  - port: 9181
    # nodePort: 30030
    name: oss
  selector:
    app: oss
---
apiVersion: v1
kind: Service
metadata:
  name: oss
  labels:
    app: oss
spec:
  clusterIP: None
  ports:
  - port: 9181
    name: oss
  selector:
    app: oss
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oss
spec:
  serviceName: 'oss'
  # n instances
  replicas: 2
  selector:
    matchLabels:
      app: oss
  template:
    metadata:
      labels:
        app: oss
    spec:
      containers:
      - name: oss
        image: echopdevecwur.azurecr.cn/qiyuesuo:latest
        ports:
        - containerPort: 9181
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 9181
        volumeMounts:
        - name: config-volume
          mountPath: /opt/qiyuesuo/config/
        - name: license-volume
          mountPath: /opt/qiyuesuo/license/
        - name: log-volume
          mountPath: /opt/qiyuesuo/logs/
        - name: data-volume
          mountPath: /opt/qiyuesuo/data/
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-pvc
            readOnly: false
        - name: license-volume
          persistentVolumeClaim:
            claimName: license-pvc
            readOnly: false
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc
            readOnly: false
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
            readOnly: false
