apiVersion: apps/v1
kind: Deployment
metadata:
  name: oss-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oss-pod
  template:
    metadata:
      labels:
        app: oss-pod
    spec:
      containers:
      - name: oss-container
        imagePullPolicy: Always
        image: echopdevecwur.azurecr.cn/qiyuesuo:latest
        command: ["java"]
        args:
          - "-Xms2048m"
          - "-Xmx2048m"
          - "-Dloader.path=/opt/qiyuesuo/libs"
          - "-XX:+PrintGCDetails"
          - "-Xloggc:/opt/qiyuesuo/logs/gc/privoss.log"
          - "-XX:+PrintGCDateStamps"
          - "-XX:-OmitStackTraceInFastThrow"
          - "-Djava.security.egd=file:/dev/./urandom"
          - "-Dspring.profiles.active=production"
          - "-Dqiyuesuo.logdir=/opt/qiyuesuo/logs"
          - "-Dqiyuesuo.cluster.members=127.0.0.1"
          - "-jar"
          - "/opt/qiyuesuo/privoss.jar"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
        ports:
        - containerPort: 5701
        - containerPort: 9180
        - containerPort: 9181
        - containerPort: 9182
---
apiVersion: v1
kind: Service
metadata:
  name: oss-service  
spec:
  type: LoadBalancer
  # type: ClusterIP
  externalTrafficPolicy: Local
  selector:
    app: oss-pod
  ports:
  - name: hazelcast
    protocol: TCP
    port: 5701
    targetPort: 5701
  - name: app
    protocol: TCP
    port: 9180
    targetPort: 9180
  - name: oss
    protocol: TCP
    port: 9181
    targetPort: 9181
  - name: open
    protocol: TCP
    port: 9182
    targetPort: 9182
