apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # 更新时允许最大激增的容器数，默认 replicas 的 1/4 向上取整
      maxUnavailable: 0  # 更新时允许最大 unavailable 容器数，默认 replicas 的 1/4 向下取整
  selector:
    matchLabels:
      app: hazelcast-pod
  template:
    metadata:
      labels:
        app: hazelcast-pod
    spec:
      containers:
      - name: hazelcast-container
        imagePullPolicy: Always
        image: echopdevecwur.azurecr.cn/hazelcast:latest
        command: ["java"]
        args:
          - "-Xms1024m"
          - "-Xmx1024m"
          - "-Dloader.path=/opt/qiyuesuo/libs"
          - "-XX:+PrintGCDetails"
          - "-Xloggc:/opt/qiyuesuo/logs/gc/hazelcast.log"
          - "-XX:+PrintGCDateStamps"
          - "-XX:-OmitStackTraceInFastThrow"
          - "-Djava.security.egd=file:/dev/./urandom"
          # - "-Dspring.profiles.active=production"
          - "-Dqiyuesuo.logdir=/opt/qiyuesuo/logs"
          - "-DeurekaServer=http://eureka:8761/eureka"
          - "-jar"
          - "/opt/qiyuesuo/hazelcast.jar"
        envFrom:
        - configMapRef:
            name: cm-hazelcast
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service  
spec:
  # type: LoadBalancer
  # externalTrafficPolicy: Local
  type: ClusterIP
  selector:
    app: hazelcast-pod
  ports:
  - name: hazelcast
    protocol: TCP
    port: 5701
    targetPort: 5701
